name: AntiUUIDSpoof
version: 1.2
main: io.github.lumine1909.AntiUUIDSpoof
api-version: 1.13
authors:
  - Lumine1909
commands:
  antiuuidspoof:
    aliases:
      - aus
permissions:
  handshakechecker.reload:
    default: op